version: 1.0.0.{build}
image: Visual Studio 2019
configuration: Debug
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
- cmd: dotnet tool install -g dotnet-sonarscanner
- cmd: dotnet sonarscanner begin /k:"michikeiser_MikSoft.Docua" /o:"michikeiser" /v:%APPVEYOR_BUILD_VERSION% /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="8a5532084a44050c55730e37a200ab749cf3ed79" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.cs.opencover.reportsPaths="lcov.opencover.xml"
build_script:
- cmd: dotnet build MikSoft.Docua.sln
- cmd: dotnet test MikSoft.Docua.Common.Services.UnitTests\MikSoft.Docua.Common.Services.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../lcov
after_build:
- cmd: dotnet sonarscanner end /d:sonar.login="8a5532084a44050c55730e37a200ab749cf3ed79"