//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace MikSoft.Docua.Common.Data.FileSystem.Metadata.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Metadata {
        
        private string docuaVersionField;
        
        private string contentFilenameField;
        
        private string ocrFilenameField;
        
        private string idField;
        
        private string documentNumberField;
        
        private string nameField;
        
        private System.DateTime dateField;
        
        private PropertyValue[] propertyValuesField;
        
        private string[] tagsField;
        
        private System.DateTime addedAtField;
        
        private string addedFromField;
        
        /// <remarks/>
        public string DocuaVersion {
            get {
                return this.docuaVersionField;
            }
            set {
                this.docuaVersionField = value;
            }
        }
        
        /// <remarks/>
        public string ContentFilename {
            get {
                return this.contentFilenameField;
            }
            set {
                this.contentFilenameField = value;
            }
        }
        
        /// <remarks/>
        public string OcrFilename {
            get {
                return this.ocrFilenameField;
            }
            set {
                this.ocrFilenameField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PropertyValue", IsNullable=false)]
        public PropertyValue[] PropertyValues {
            get {
                return this.propertyValuesField;
            }
            set {
                this.propertyValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable=false)]
        public string[] Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime AddedAt {
            get {
                return this.addedAtField;
            }
            set {
                this.addedAtField = value;
            }
        }
        
        /// <remarks/>
        public string AddedFrom {
            get {
                return this.addedFromField;
            }
            set {
                this.addedFromField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PropertyValue {
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PropertyValues {
        
        private PropertyValue[] propertyValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PropertyValue")]
        public PropertyValue[] PropertyValue {
            get {
                return this.propertyValueField;
            }
            set {
                this.propertyValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Tags {
        
        private string[] tagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Tag")]
        public string[] Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
    }
}
